import { expect, test, type Page } from '@playwright/test';
import type { Source } from '../../src/shared/protocol';

type Case = { name:string; source:Source; marker:string; viewport?:'mobile'; interact?:(page:Page)=>Promise<void> };

const base = `*{box-sizing:border-box}body{margin:0;background:#f7f8fc;color:#172033;font-family:Inter,Arial,sans-serif}button,input{font:inherit}`;
const cases:Case[] = [
  {name:'auth form',marker:'Continue with email',source:{
    html:`<main class="shell"><section class="panel"><div class="brand">S<sup>+</sup></div><p class="eyebrow">WELCOME BACK</p><h1>Sign in to your workspace</h1><p class="muted">Use your work email to continue.</p><form><label>Work email<input type="email" value="maya@studio.co"></label><label>Password<input type="password" value="password"></label><div class="options"><label class="check"><input type="checkbox" checked>Remember me</label><a>Forgot password?</a></div><button>Continue with email <span>→</span></button></form><p class="join">New here? <b>Create an account</b></p></section><aside><span class="orb"></span><blockquote>“The calmest way to plan a busy week.”</blockquote><p>— The Paper Room</p></aside></main>`,
    css:`${base}.shell{min-height:680px;display:grid;grid-template-columns:1.1fr .9fr;padding:28px}.panel{background:#fff;border:1px solid #e6e9f1;border-radius:22px;padding:60px 13%;}.brand{width:38px;height:38px;display:grid;place-items:center;background:#4c46e5;color:#fff;border-radius:12px;font-weight:800}.brand sup{color:#b9f5d0}.eyebrow{margin-top:64px;color:#6865ce;font-size:11px;font-weight:800;letter-spacing:1.6px}h1{max-width:370px;font-size:39px;line-height:1.08;letter-spacing:-1.5px;margin:15px 0}.muted{color:#697386}form{max-width:380px;margin-top:36px}label{display:grid;gap:8px;font-size:12px;font-weight:700;margin-top:18px}input{width:100%;padding:13px 14px;border:1px solid #d8ddea;border-radius:9px;color:#344054}.options{display:flex;justify-content:space-between;align-items:center;margin:17px 0 24px;color:#5853ce;font-size:12px}.check{display:flex;align-items:center;gap:7px;margin:0;color:#697386;font-weight:500}.check input{width:14px}button{border:0;border-radius:9px;background:#4c46e5;color:#fff;width:100%;padding:14px 16px;font-weight:700;display:flex;justify-content:space-between}.join{font-size:12px;color:#697386;margin-top:32px}.join b{color:#4c46e5}aside{margin:14px 0 14px -110px;border-radius:18px;background:linear-gradient(145deg,#5b55ed,#29236c);padding:60px;display:flex;flex-direction:column;justify-content:flex-end;color:#fff;overflow:hidden;position:relative}.orb{position:absolute;width:420px;height:420px;border:1px solid #b4b0ff;border-radius:50%;top:-115px;right:-130px}blockquote{position:relative;max-width:320px;font:italic 29px/1.18 Georgia,serif;letter-spacing:-1px;margin:0}aside p{position:relative;color:#c8c6ff;font-size:12px}`,
    js:''}},
  {name:'saas dashboard',marker:'MONTHLY REVENUE',source:{
    html:`<div class="dashboard"><aside class="side"><b>orbit.</b><nav><a class="active">Overview</a><a>Orders</a><a>Customers</a><a>Campaigns</a></nav><div class="user"><span>ML</span><div><b>Maya Lee</b><small>Admin</small></div></div></aside><main><header><div><p class="eyebrow">TUESDAY, SEPTEMBER 28</p><h1>Good morning, Maya <span>✦</span></h1></div><button class="export">Export report</button></header><section class="stats"><article><small>MONTHLY REVENUE</small><h2>$84,210</h2><p class="up">↗ 12.5% <em>vs. last month</em></p></article><article><small>ACTIVE SUBSCRIPTIONS</small><h2>2,846</h2><p class="up">↗ 8.2% <em>vs. last month</em></p></article><article><small>CHURN RATE</small><h2>1.8%</h2><p class="down">↘ 0.4% <em>vs. last month</em></p></article></section><section class="chart"><div class="chart-head"><div><small>MONTHLY REVENUE</small><h2>Revenue over time</h2></div><div class="legend"><i></i> Revenue <span>Apr — Sep 2026</span></div></div><svg viewBox="0 0 720 240" role="img" aria-label="Revenue line chart"><path class="grid" d="M0 30h720M0 100h720M0 170h720M0 230h720"/><path class="area" d="M0 196C80 185 98 152 159 163S250 122 309 138s81-52 157-40 91-44 151-48 71-5 103-34v214H0z"/><path class="line" d="M0 196C80 185 98 152 159 163S250 122 309 138s81-52 157-40 91-44 151-48 71-5 103-34"/><circle cx="720" cy="16" r="5"/></svg><div class="months"><span>Apr</span><span>May</span><span>Jun</span><span>Jul</span><span>Aug</span><span>Sep</span></div></section><section class="activity"><h2>Recent activity</h2><div><span class="avatar yellow">AR</span><p><b>Arun Rao</b> upgraded to Annual plan<small>12 minutes ago</small></p><strong>+$240.00</strong></div><div><span class="avatar purple">KW</span><p><b>Kira White</b> invited 3 teammates<small>38 minutes ago</small></p><strong class="soft">Team</strong></div></section></main></div>`,
    css:`${base}.dashboard{min-height:760px;display:grid;grid-template-columns:205px 1fr}.side{background:#182030;color:#aab4c6;padding:30px 18px;display:flex;flex-direction:column}.side>b{font-size:25px;color:#fff;letter-spacing:-1.5px;padding:0 12px}.side nav{display:grid;gap:7px;margin-top:55px}.side a{padding:11px 12px;border-radius:8px;font-size:13px}.side .active{color:#fff;background:#2d374b}.user{margin-top:auto;display:flex;align-items:center;gap:10px;padding:12px}.user>span,.avatar{display:grid;place-items:center;width:31px;height:31px;border-radius:50%;font-size:10px;font-weight:800;color:#fff;background:#5d66d8}.user div{display:grid;gap:2px}.user b{font-size:11px;color:#fff}.user small{font-size:10px}main{padding:43px 5%;background:#f8f9fc}header{display:flex;align-items:flex-start;justify-content:space-between}.eyebrow,small{font-size:10px;letter-spacing:1.1px;color:#7f8a9d}.eyebrow{font-weight:800}h1{margin:9px 0;font-size:31px;letter-spacing:-1px}.export{border:1px solid #dce1ec;background:#fff;border-radius:8px;padding:10px 14px;font-size:12px;color:#384152}.stats{display:grid;grid-template-columns:repeat(3,1fr);gap:16px;margin:31px 0 19px}.stats article,.chart,.activity{background:#fff;border:1px solid #e7eaf1;border-radius:12px;padding:21px}.stats h2{margin:13px 0 9px;font-size:25px;letter-spacing:-.8px}.stats p{font-size:11px;margin:0}.up{color:#119566}.down{color:#e36b74}.stats em{font-style:normal;color:#98a1b0;margin-left:5px}.chart{min-height:335px}.chart-head{display:flex;justify-content:space-between;align-items:center}.chart h2,.activity h2{font-size:15px;margin:6px 0}.legend{font-size:11px;color:#6f798b}.legend i{display:inline-block;width:8px;height:8px;border-radius:50%;background:#625ee8}.legend span{color:#9da5b1;margin-left:10px}svg{width:100%;height:220px;margin-top:10px}.grid{stroke:#ebedf3;stroke-width:1}.area{fill:#625ee818}.line{fill:none;stroke:#625ee8;stroke-width:3}.chart circle{fill:#625ee8;stroke:#fff;stroke-width:3}.months{display:flex;justify-content:space-between;color:#9da5b1;font-size:10px}.activity{margin-top:18px}.activity>div{display:flex;align-items:center;gap:12px;border-top:1px solid #edf0f5;padding:12px 0}.activity p{display:grid;gap:2px;flex:1;margin:0;font-size:11px}.activity p small{letter-spacing:0}.activity strong{font-size:11px;color:#139368}.activity .soft{color:#9d71d9}.yellow{background:#e4a843}.purple{background:#9877dc}`,
    js:''}},
  {name:'data table',marker:'Invoice #1048',source:{
    html:`<main class="table-page"><header><div><p class="eyebrow">FINANCE / INVOICES</p><h1>Invoices</h1><p class="sub">Track payments and keep your books tidy.</p></div><button>+ New invoice</button></header><section class="tools"><div class="search">⌕ <span>Search invoices…</span></div><button class="filter">Filter <b>3</b></button><button class="filter">Sep 2026⌄</button></section><section class="table-card"><table><thead><tr><th>INVOICE</th><th>CUSTOMER</th><th>ISSUED</th><th>AMOUNT</th><th>STATUS</th><th></th></tr></thead><tbody><tr><td><b>Invoice #1048</b><small>Pro plan · annual</small></td><td><div class="person"><i class="one">SC</i>Silver Coast</div></td><td>Sep 28, 2026</td><td><b>$2,400.00</b></td><td><span class="pill paid">Paid</span></td><td>•••</td></tr><tr><td><b>Invoice #1047</b><small>Growth plan · monthly</small></td><td><div class="person"><i class="two">NN</i>Nora North</div></td><td>Sep 25, 2026</td><td><b>$480.00</b></td><td><span class="pill pending">Pending</span></td><td>•••</td></tr><tr><td><b>Invoice #1046</b><small>Starter plan · monthly</small></td><td><div class="person"><i class="three">AV</i>Atlas Ventures</div></td><td>Sep 22, 2026</td><td><b>$120.00</b></td><td><span class="pill overdue">Overdue</span></td><td>•••</td></tr><tr><td><b>Invoice #1045</b><small>Pro plan · annual</small></td><td><div class="person"><i class="four">CH</i>Common House</div></td><td>Sep 18, 2026</td><td><b>$2,400.00</b></td><td><span class="pill paid">Paid</span></td><td>•••</td></tr></tbody></table><footer><span>Showing <b>1–4</b> of 32 invoices</span><div><button disabled>← Previous</button><button>Next →</button></div></footer></section></main>`,
    css:`${base}.table-page{min-height:680px;padding:56px 6%;background:#fbfcfe}header{display:flex;justify-content:space-between;align-items:flex-start}.eyebrow{font-size:10px;font-weight:800;letter-spacing:1.5px;color:#736cd9}h1{margin:9px 0 6px;font-size:34px;letter-spacing:-1.2px}.sub{margin:0;color:#778196;font-size:13px}button{border:0;background:#5b55d9;color:#fff;border-radius:8px;padding:11px 15px;font-size:12px;font-weight:700}.tools{display:flex;gap:10px;margin:35px 0 15px}.search{width:250px;padding:10px 12px;background:#fff;border:1px solid #e2e6ef;border-radius:8px;color:#a1a9b7;font-size:12px}.filter{background:#fff;color:#5c6575;border:1px solid #e2e6ef;font-weight:500}.filter b{background:#edeafd;color:#5b55d9;border-radius:10px;padding:2px 6px;margin-left:5px}.table-card{border:1px solid #e1e5ee;border-radius:12px;background:#fff;overflow:hidden}table{width:100%;border-collapse:collapse;text-align:left}th{padding:15px 18px;background:#f7f8fb;color:#8c95a5;font-size:9px;letter-spacing:1px}td{padding:16px 18px;border-top:1px solid #edf0f4;font-size:12px;color:#5d6878}td b{color:#293246;font-size:12px}td small{display:block;color:#a0a8b5;font-size:10px;margin-top:4px}.person{display:flex;align-items:center;gap:8px;color:#344054}.person i{display:grid;place-items:center;width:25px;height:25px;border-radius:50%;font-style:normal;font-size:8px;color:#fff}.one{background:#6571d8}.two{background:#e39754}.three{background:#5aa98a}.four{background:#b778bc}.pill{display:inline-block;padding:4px 9px;border-radius:20px;font-size:10px;font-weight:700}.paid{color:#087d55;background:#e3f7ee}.pending{color:#9b6900;background:#fff2cc}.overdue{color:#c04850;background:#fee9ea}footer{display:flex;align-items:center;justify-content:space-between;padding:15px 18px;border-top:1px solid #edf0f4;color:#929aa8;font-size:11px}footer b{color:#4c5567}footer button{background:#fff;color:#637083;border:1px solid #e2e6ef;padding:7px 10px;font-size:10px;margin-left:6px}footer button:disabled{opacity:.45}`,
    js:''}},
  {name:'commerce grid',marker:'Linen Armchair',source:{
    html:`<main class="shop"><header><b>nook</b><nav>New arrivals&nbsp;&nbsp;&nbsp; Furniture&nbsp;&nbsp;&nbsp; Lighting&nbsp;&nbsp;&nbsp; Objects</nav><span>Search&nbsp;&nbsp; Bag (2)</span></header><section class="intro"><p>THE AUTUMN EDIT</p><h1>Objects for a<br>slower home.</h1><button>Shop collection ↗</button></section><section class="products"><article><div class="photo chair"><span>NEW</span><i>♡</i></div><h2>Linen Armchair</h2><p>Warm oat · $1,280</p></article><article><div class="photo lamp"><i>♡</i></div><h2>Bell Table Lamp</h2><p>Fog white · $320</p></article><article><div class="photo vase"><span>ONLY 4 LEFT</span><i>♡</i></div><h2>Terracotta Vessel</h2><p>Clay · $84</p></article></section></main>`,
    css:`${base}.shop{min-height:700px;background:#f5f0e8;color:#243127;padding:0 5%}header{height:76px;border-bottom:1px solid #dcd5c8;display:flex;align-items:center;justify-content:space-between;font-size:11px}header>b{font:700 28px Georgia,serif;letter-spacing:-2px}header span{font-size:10px}.intro{text-align:center;padding:55px 0 46px}.intro p{letter-spacing:1.7px;font-size:9px;color:#6f7b69}.intro h1{font:400 48px/1.04 Georgia,serif;letter-spacing:-2.2px;margin:15px}.intro button{border:0;background:#2d3b2c;color:#fff;padding:12px 18px;font-size:10px}.products{display:grid;grid-template-columns:repeat(3,1fr);gap:20px}.photo{height:300px;position:relative;overflow:hidden;background:#ded8cc}.photo span,.photo i{position:absolute;z-index:1;top:12px;font-size:9px;font-style:normal}.photo span{left:12px;background:#f8f5ef;padding:5px 7px}.photo i{right:12px;font-size:18px}.chair:before{content:"";position:absolute;width:130px;height:110px;background:#bda888;border-radius:58px 58px 26px 26px;left:50%;bottom:64px;transform:translateX(-50%);box-shadow:0 42px 0 -12px #a18d71}.chair:after{content:"";position:absolute;width:180px;height:28px;border-radius:50%;background:#8a837822;left:50%;bottom:22px;transform:translateX(-50%)}.lamp{background:#e4e7de}.lamp:before{content:"";position:absolute;left:50%;bottom:44px;width:72px;height:130px;background:#b6b7ab;border-radius:40px 40px 8px 8px;transform:translateX(-50%)}.lamp:after{content:"";position:absolute;left:50%;bottom:164px;border-left:92px solid transparent;border-right:92px solid transparent;border-bottom:110px solid #f4f0e8;transform:translateX(-50%)}.vase{background:#d9c6b1}.vase:before{content:"";position:absolute;width:92px;height:155px;background:#b96f4e;border-radius:55% 55% 40% 40%;left:50%;bottom:35px;transform:translateX(-50%)}.vase:after{content:"";position:absolute;width:170px;height:30px;border-radius:50%;background:#7d5b4722;left:50%;bottom:18px;transform:translateX(-50%)}article h2{font-size:13px;margin:13px 0 4px;font-weight:600}article p{font-size:11px;color:#758071;margin:0}`,
    js:''}},
  {name:'interactive analytics',marker:'Conversion funnel',source:{
    html:`<main class="analytics"><header><div><span class="logo">signal</span><span class="divider"></span><b>Analytics</b></div><button id="period">Last 30 days⌄</button></header><section class="summary"><p>PERFORMANCE</p><h1>Conversion funnel</h1><div class="toggle"><button class="selected">All traffic</button><button>Organic</button><button>Paid</button></div></section><section class="funnel"><div><p>VISITORS</p><h2>28,940</h2><span>100%</span></div><div><p>PRODUCT VIEWS</p><h2>12,508</h2><span>43.2%</span></div><div><p>CHECKOUTS</p><h2>2,174</h2><span>17.4%</span></div><div><p>PURCHASES</p><h2 id="purchases">684</h2><span>31.5%</span></div></section><section class="split"><article><h2>Top channels</h2><div class="bar"><p>Direct <b>42%</b></p><i style="width:42%"></i></div><div class="bar"><p>Organic search <b>31%</b></p><i style="width:31%"></i></div><div class="bar"><p>Newsletter <b>19%</b></p><i style="width:19%"></i></div></article><article class="note"><p id="message">Your purchase rate is 6.1% higher than the previous period.</p><button id="refresh">Refresh insights ↗</button></article></section></main>`,
    css:`${base}.analytics{min-height:650px;background:#121416;color:#f4f4ef;padding:0 6%}header{height:70px;display:flex;justify-content:space-between;align-items:center;border-bottom:1px solid #31353a;font-size:12px}.logo{font-size:20px;font-weight:800;letter-spacing:-1px}.divider{height:20px;border-left:1px solid #464a50;margin:0 15px}header button{color:#e9eceb;background:#1e2225;border:1px solid #393e44;border-radius:6px;padding:8px 11px;font-size:11px}.summary{padding:46px 0 32px}.summary>p{color:#a9e584;font-size:9px;letter-spacing:1.4px}.summary h1{font-size:38px;letter-spacing:-1.5px;margin:10px 0 25px}.toggle{display:flex;gap:8px}.toggle button{background:transparent;color:#9aa2a0;border:1px solid #3c4244;border-radius:20px;padding:7px 13px;font-size:10px}.toggle .selected{background:#d8f1c6;color:#1d3022;border-color:#d8f1c6}.funnel{display:grid;grid-template-columns:1.6fr 1.25fr 1fr .75fr;height:180px;align-items:end;gap:4px}.funnel>div{padding:16px;background:#9be477;color:#17301c;min-height:100%}.funnel>div:nth-child(2){min-height:74%;background:#bbec9e}.funnel>div:nth-child(3){min-height:51%;background:#d0f2bd}.funnel>div:nth-child(4){min-height:36%;background:#e2f7d3}.funnel p{font-size:9px;letter-spacing:1px;margin:0}.funnel h2{font-size:29px;letter-spacing:-1px;margin:8px 0}.funnel span{font-size:10px}.split{display:grid;grid-template-columns:1.5fr 1fr;gap:14px;margin-top:24px}.split article{border:1px solid #32383a;border-radius:10px;padding:19px}.split h2{font-size:13px;margin:0 0 16px}.bar p{display:flex;justify-content:space-between;color:#cbd2cf;font-size:11px;margin:12px 0 6px}.bar i{display:block;height:5px;background:#a9e584;border-radius:10px}.note{display:flex;flex-direction:column;justify-content:space-between;background:#1b2420}.note p{font-size:14px;line-height:1.5;color:#d7e4da;margin:0}.note button{align-self:flex-start;border:0;background:transparent;color:#a9e584;padding:0;font-size:10px}`,
    js:`document.querySelector('#refresh').addEventListener('click',()=>{document.querySelector('#message').textContent='Insight refreshed: purchases accelerated after the Thursday newsletter.';document.querySelector('#purchases').textContent='712';});`},
    interact:async page=>{const frame=page.frameLocator('iframe[title="Live preview"]');await frame.getByRole('button',{name:/Refresh insights/}).click();await expect(frame.getByText(/Insight refreshed/)).toBeVisible();}},
  {name:'mobile app state',marker:'YOUR BALANCE',viewport:'mobile',source:{
    html:`<main class="mobile"><header><span class="avatar">JD</span><div><small>GOOD EVENING</small><h1>Jamie Doe</h1></div><button aria-label="Notifications">◌</button></header><section class="balance"><p>YOUR BALANCE</p><h2>$ 8,420.75</h2><span>↗ 4.2% this month</span><div class="card-number">•••• &nbsp; 4832 <i>VISA</i></div></section><section class="quick"><button>＋<span>Send</span></button><button>↓<span>Request</span></button><button>⌘<span>Scan</span></button><button>•••<span>More</span></button></section><section class="transactions"><div class="title"><h2>Recent activity</h2><button>See all</button></div><article><i class="coffee">☕</i><p><b>Olive Coffee</b><small>Today · 09:41</small></p><strong>−$5.80</strong></article><article><i class="income">↙</i><p><b>Salary</b><small>Yesterday · 08:00</small></p><strong class="plus">+$4,600.00</strong></article><article><i class="music">♪</i><p><b>SoundCloud</b><small>Sep 24 · Subscription</small></p><strong>−$9.99</strong></article></section><nav><span>⌂<b>Home</b></span><span>▥<b>Cards</b></span><span>⌁<b>Insights</b></span><span>◯<b>Profile</b></span></nav></main>`,
    css:`${base}body{background:#e9ecf7}.mobile{min-height:730px;background:#fdfdff;padding:29px 20px 80px;color:#202941}header{display:flex;align-items:center;gap:11px}header .avatar{display:grid;place-items:center;width:39px;height:39px;border-radius:50%;background:#d9dafb;color:#4944b9;font-size:10px;font-weight:800}header div{flex:1}header small{font-size:8px;letter-spacing:1.3px;color:#8b91a6}h1{font-size:16px;margin:2px 0}header button{border:0;background:#f0f1fb;border-radius:50%;width:35px;height:35px}.balance{margin-top:29px;border-radius:20px;padding:22px;background:linear-gradient(135deg,#665fe7,#302b94);color:#fff}.balance p{font-size:9px;letter-spacing:1.3px;color:#d8d6ff;margin:0}.balance h2{font-size:30px;letter-spacing:-1px;margin:8px 0}.balance>span{font-size:10px;color:#b8f1cb}.card-number{border-top:1px solid #ffffff42;margin-top:21px;padding-top:13px;font-size:12px;letter-spacing:1.5px}.card-number i{float:right;font:bold 11px Arial}.quick{display:grid;grid-template-columns:repeat(4,1fr);gap:10px;margin:23px 0}.quick button{display:grid;place-items:center;gap:5px;padding:10px 2px;border:0;background:#f2f3fb;border-radius:13px;color:#514bc4;font-size:19px}.quick span{font-size:9px;color:#5f6680}.transactions{margin-top:7px}.title{display:flex;justify-content:space-between;align-items:center}.title h2{font-size:15px}.title button{border:0;background:transparent;color:#5c55d2;font-size:10px}.transactions article{display:flex;align-items:center;gap:11px;padding:13px 0;border-bottom:1px solid #eef0f5}.transactions i{display:grid;place-items:center;width:35px;height:35px;border-radius:11px;background:#fff2df;font-style:normal;font-size:14px}.transactions .income{background:#e3f8ed;color:#14835b}.transactions .music{background:#eee9ff;color:#694dda}.transactions p{display:grid;gap:3px;flex:1;margin:0}.transactions b{font-size:11px}.transactions small{font-size:9px;color:#969daf}.transactions strong{font-size:11px}.plus{color:#149062}nav{position:absolute;bottom:0;left:0;width:100%;height:62px;border-top:1px solid #eceef5;background:#fff;display:flex;justify-content:space-around;padding-top:10px}nav span{display:grid;place-items:center;gap:3px;font-size:15px;color:#878ea4}nav span:first-child{color:#564fd0}nav b{font-size:8px;font-weight:500}`,
    js:''}},
];

async function load(page:Page, source:Source) {
  await page.goto('/');
  await page.evaluate(value=>localStorage.setItem('html-to-figma:draft:v1',JSON.stringify(value)),source);
  await page.reload();
  await page.getByRole('button',{name:'Run code'}).click();
  await expect(page.getByRole('status')).toContainText('up to date');
}

async function payload(page:Page) {
  await page.getByRole('button',{name:'Copy to Figma'}).click();
  await expect(page.getByRole('status')).toContainText('Copied!',{timeout:40000});
  const encoded=await page.evaluate(async()=>{
    const [item]=await navigator.clipboard.read();
    const html=await(await item.getType('text/html')).text();
    const data=new DOMParser().parseFromString(html,'text/html').querySelector('[data-h2d]')?.getAttribute('data-h2d') ?? '';
    return data.match(/<!--\(figh2d\)(.*?)\(\/figh2d\)-->/s)?.[1] ?? '';
  });
  return Buffer.from(encoded,'base64').toString('utf8');
}

for (const entry of cases) test(`captures ${entry.name} as Figma clipboard layers`,async ({page})=>{
  await load(page,entry.source);
  if(entry.viewport==='mobile') await page.getByRole('button',{name:'Mobile viewport'}).click();
  if(entry.interact) await entry.interact(page);
  const captured=await payload(page);
  expect(captured).toContain(entry.marker);
  expect(JSON.parse(captured).viewportRect.width).toBe(entry.viewport==='mobile'?390:1024);
  expect(captured).toContain('"childNodes"');
});
